# Application Settings
application:
  foo: bar


# Database Settings
spring:
  datasource:
    hikari:
      maximum-pool-size: 4
      minimum-idle: 1
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./database/sample
    username: admin
    password: admin

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true

  jpa:
    open-in-view: true
    database: h2
    hibernate:
      ddl-auto: update